// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jukfcbxcxeoihogfsnyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1a2ZjYnhjeGVvaWhvZ2ZzbnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3Njk3ODEsImV4cCI6MjA3MTM0NTc4MX0.FD7qZt-dfSpDMf8g09CQuRkL0aNf5TuGYL1-KwkaKcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});